#!/usr/bin/env bash
# Provision AWS resources on LocalStack using Terraform.
# Usage: ./provision-localstack.sh [terraform_dir]
# Defaults to .deploy/dev if no directory specified.
set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || echo '.')"
TERRAFORM_DIR="${1:-${REPO_ROOT}/.deploy/dev}"
LOCALSTACK_PORT="${LOCALSTACK_PORT:-4566}"
LOCALSTACK_ENDPOINT="http://localhost:${LOCALSTACK_PORT}"

# --- Preflight checks ---

if ! command -v terraform &>/dev/null; then
  echo "ERROR: Terraform not found. Install with:"
  echo "  brew install terraform"
  exit 1
fi

if ! curl -sf "${LOCALSTACK_ENDPOINT}/_localstack/health" &>/dev/null; then
  echo "ERROR: LocalStack is not running at ${LOCALSTACK_ENDPOINT}"
  echo "Start it first with: ./start-localstack.sh"
  exit 1
fi

if [[ ! -d "$TERRAFORM_DIR" ]]; then
  echo "ERROR: Terraform directory not found: $TERRAFORM_DIR"
  echo "Available directories:"
  find "${REPO_ROOT}/.deploy" -maxdepth 1 -type d 2>/dev/null || echo "  (none — .deploy/ does not exist)"
  exit 1
fi

# --- Create override for LocalStack endpoints ---

OVERRIDE_FILE="${TERRAFORM_DIR}/localstack_override.tf"

echo "Creating LocalStack provider override at: ${OVERRIDE_FILE}"
cat > "$OVERRIDE_FILE" <<EOF
# Auto-generated by prepare-for-deployment skill.
# This file overrides the AWS provider to point at LocalStack.
# DO NOT commit this file.

terraform {
  backend "local" {}
}

provider "aws" {
  access_key = "test"
  secret_key = "test"
  region     = "eu-central-1"

  skip_credentials_validation = true
  skip_metadata_api_check     = true
  skip_requesting_account_id  = true

  endpoints {
    s3             = "${LOCALSTACK_ENDPOINT}"
    dynamodb       = "${LOCALSTACK_ENDPOINT}"
    lambda         = "${LOCALSTACK_ENDPOINT}"
    sqs            = "${LOCALSTACK_ENDPOINT}"
    sns            = "${LOCALSTACK_ENDPOINT}"
    iam            = "${LOCALSTACK_ENDPOINT}"
    sts            = "${LOCALSTACK_ENDPOINT}"
    secretsmanager = "${LOCALSTACK_ENDPOINT}"
    cloudwatch     = "${LOCALSTACK_ENDPOINT}"
    logs           = "${LOCALSTACK_ENDPOINT}"
    ecs            = "${LOCALSTACK_ENDPOINT}"
    ecr            = "${LOCALSTACK_ENDPOINT}"
    rds            = "${LOCALSTACK_ENDPOINT}"
  }
}
EOF

# Add to .gitignore if not already there
GITIGNORE="${REPO_ROOT}/.gitignore"
if [[ -f "$GITIGNORE" ]]; then
  if ! grep -qF "localstack_override.tf" "$GITIGNORE"; then
    echo "localstack_override.tf" >> "$GITIGNORE"
    echo "Added localstack_override.tf to .gitignore"
  fi
else
  echo "localstack_override.tf" > "$GITIGNORE"
  echo "Created .gitignore with localstack_override.tf"
fi

# --- Run Terraform ---

echo ""
echo "Initializing Terraform in: ${TERRAFORM_DIR}"
cd "$TERRAFORM_DIR"

terraform init -reconfigure -input=false

echo ""
echo "Planning..."
terraform plan -out=localstack.tfplan -input=false

echo ""
echo "Applying..."
terraform apply -input=false localstack.tfplan

echo ""
echo "Provisioning complete!"
echo "Resources created on LocalStack at ${LOCALSTACK_ENDPOINT}"

# --- Cleanup plan file ---
rm -f localstack.tfplan

echo ""
echo "To tear down: terraform destroy -auto-approve"
echo "To remove override: rm ${OVERRIDE_FILE}"
