"""user disable and erase tombstone fields

Revision ID: 6c0140842509
Revises: 8b85d1f617e9
Create Date: 2026-09-05 00:31:30.891054

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6c0140842509'
down_revision: str | Sequence[str] | None = '8b85d1f617e9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('erased_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'erased_at')
    op.drop_column('users', 'disabled_at')
    # ### end Alembic commands ###
