"""invites and system settings

Revision ID: bc685ea622fe
Revises: 9fa7eeb375ca
Create Date: 2026-09-02 22:51:24.736016

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op
from app.security.system_settings import DEFAULT_INVITE_EXPIRY_DAYS, INVITE_EXPIRY_DAYS_KEY

# revision identifiers, used by Alembic.
revision: str = 'bc685ea622fe'
down_revision: str | Sequence[str] | None = '9fa7eeb375ca'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('invites',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('invited_by_user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['invited_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_invites_email'), 'invites', ['email'], unique=False)
    op.create_table('invite_roles',
    sa.Column('invite_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['invite_id'], ['invites.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('invite_id', 'role_id')
    )
    # ### end Alembic commands ###

    system_settings = sa.table(
        "system_settings",
        sa.column("key", sa.String()),
        sa.column("value", sa.String()),
    )
    op.get_bind().execute(
        system_settings.insert().values(
            key=INVITE_EXPIRY_DAYS_KEY, value=str(DEFAULT_INVITE_EXPIRY_DAYS)
        )
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invite_roles')
    op.drop_index(op.f('ix_invites_email'), table_name='invites')
    op.drop_table('invites')
    op.drop_table('system_settings')
    # ### end Alembic commands ###
